var buzz={defaults:{autoplay:!1,duration:5E3,formats:[],loop:!1,placeholder:"--",preload:"metadata",volume:80},types:{mp3:"audio/mpeg",ogg:"audio/ogg",wav:"audio/wav",aac:"audio/aac",m4a:"audio/x-m4a"},sounds:[],el:document.createElement("audio"),sound:function(a,b){function c(a){for(var b=[],c=a.length-1,f=0;f<=c;f++)b.push({start:a.start(c),end:a.end(c)});return b}function f(a,b){var c=document.createElement("source");c.src=b;buzz.types[b.split(".").pop()]&&(c.type=buzz.types[b.split(".").pop()]);
a.appendChild(c)}var b=b||{},d=0,g=[],m={},i=buzz.isSupported();this.load=function(){if(!i)return this;this.sound.load();return this};this.play=function(){if(!i)return this;this.sound.play();return this};this.togglePlay=function(){if(!i)return this;this.sound.paused?this.sound.play():this.sound.pause();return this};this.pause=function(){if(!i)return this;this.sound.pause();return this};this.isPaused=function(){return!i?null:this.sound.paused};this.stop=function(){if(!i)return this;this.setTime(this.getDuration());
this.sound.pause();return this};this.isEnded=function(){return!i?null:this.sound.ended};this.loop=function(){if(!i)return this;this.sound.loop="loop";this.bind("ended.buzzloop",function(){this.currentTime=0;this.play()});return this};this.unloop=function(){if(!i)return this;this.sound.removeAttribute("loop");this.unbind("ended.buzzloop");return this};this.mute=function(){if(!i)return this;this.sound.muted=!0;return this};this.unmute=function(){if(!i)return this;this.sound.muted=!1;return this};this.toggleMute=
function(){if(!i)return this;this.sound.muted=!this.sound.muted;return this};this.isMuted=function(){return!i?null:this.sound.muted};this.setVolume=function(a){if(!i)return this;0>a&&(a=0);100<a&&(a=100);this.volume=a;this.sound.volume=a/100;return this};this.getVolume=function(){return!i?this:this.volume};this.increaseVolume=function(a){return this.setVolume(this.volume+(a||1))};this.decreaseVolume=function(a){return this.setVolume(this.volume-(a||1))};this.setTime=function(a){if(!i)return this;
this.whenReady(function(){this.sound.currentTime=a});return this};this.getTime=function(){if(!i)return null;var a=Math.round(100*this.sound.currentTime)/100;return isNaN(a)?buzz.defaults.placeholder:a};this.setPercent=function(a){return!i?this:this.setTime(buzz.fromPercent(a,this.sound.duration))};this.getPercent=function(){if(!i)return null;var a=Math.round(buzz.toPercent(this.sound.currentTime,this.sound.duration));return isNaN(a)?buzz.defaults.placeholder:a};this.setSpeed=function(a){if(!i)return this;
this.sound.playbackRate=a};this.getSpeed=function(){return!i?null:this.sound.playbackRate};this.getDuration=function(){if(!i)return null;var a=Math.round(100*this.sound.duration)/100;return isNaN(a)?buzz.defaults.placeholder:a};this.getPlayed=function(){return!i?null:c(this.sound.played)};this.getBuffered=function(){return!i?null:c(this.sound.buffered)};this.getSeekable=function(){return!i?null:c(this.sound.seekable)};this.getErrorCode=function(){return i&&this.sound.error?this.sound.error.code:0};
this.getErrorMessage=function(){if(!i)return null;switch(this.getErrorCode()){case 1:return"MEDIA_ERR_ABORTED";case 2:return"MEDIA_ERR_NETWORK";case 3:return"MEDIA_ERR_DECODE";case 4:return"MEDIA_ERR_SRC_NOT_SUPPORTED";default:return null}};this.getStateCode=function(){return!i?null:this.sound.readyState};this.getStateMessage=function(){if(!i)return null;switch(this.getStateCode()){case 0:return"HAVE_NOTHING";case 1:return"HAVE_METADATA";case 2:return"HAVE_CURRENT_DATA";case 3:return"HAVE_FUTURE_DATA";
case 4:return"HAVE_ENOUGH_DATA";default:return null}};this.getNetworkStateCode=function(){return!i?null:this.sound.networkState};this.getNetworkStateMessage=function(){if(!i)return null;switch(this.getNetworkStateCode()){case 0:return"NETWORK_EMPTY";case 1:return"NETWORK_IDLE";case 2:return"NETWORK_LOADING";case 3:return"NETWORK_NO_SOURCE";default:return null}};this.set=function(a,b){if(!i)return this;this.sound[a]=b;return this};this.get=function(a){return!i?null:a?this.sound[a]:this.sound};this.bind=
function(a,b){if(!i)return this;for(var a=a.split(" "),c=this,f=function(a){b.call(c,a)},d=0;d<a.length;d++){var h=a[d],j=h,h=j.split(".")[0];g.push({idx:j,func:f});this.sound.addEventListener(h,f,!0)}return this};this.unbind=function(a){if(!i)return this;for(var a=a.split(" "),b=0;b<a.length;b++)for(var c=a[b],f=c.split(".")[0],d=0;d<g.length;d++){var h=g[d].idx.split(".");if(g[d].idx==c||h[1]&&h[1]==c.replace(".",""))this.sound.removeEventListener(f,g[d].func,!0),delete g[d]}return this};this.bindOnce=
function(a,b){if(!i)return this;var c=this;m[d++]=!1;this.bind(d+a,function(){m[d]||(m[d]=!0,b.call(c));c.unbind(d+a)})};this.trigger=function(a){if(!i)return this;for(var a=a.split(" "),b=0;b<a.length;b++)for(var c=a[b],f=0;f<g.length;f++){var d=g[f].idx.split(".");if(g[f].idx==c||d[0]&&d[0]==c.replace(".","")){var h=document.createEvent("HTMLEvents");h.initEvent(d[0],!1,!0);this.sound.dispatchEvent(h)}}return this};this.fadeTo=function(a,b,c){function f(){setTimeout(function(){d<a&&g.volume<a?(g.setVolume(g.volume+=
1),f()):d>a&&g.volume>a?(g.setVolume(g.volume-=1),f()):c instanceof Function&&c.apply(g)},h)}if(!i)return this;b instanceof Function?(c=b,b=buzz.defaults.duration):b=b||buzz.defaults.duration;var d=this.volume,h=b/Math.abs(d-a),g=this;this.play();this.whenReady(function(){f()});return this};this.fadeIn=function(a,b){return!i?this:this.setVolume(0).fadeTo(100,a,b)};this.fadeOut=function(a,b){return!i?this:this.fadeTo(0,a,b)};this.fadeWith=function(a,b){if(!i)return this;this.fadeOut(b,function(){this.stop()});
a.play().fadeIn(b);return this};this.whenReady=function(a){if(!i)return null;var b=this;0===this.sound.readyState?this.bind("canplay.buzzwhenready",function(){a.call(b)}):a.call(b)};if(i){for(var h in buzz.defaults)buzz.defaults.hasOwnProperty(h)&&(b[h]=b[h]||buzz.defaults[h]);this.sound=document.createElement("audio");if(a instanceof Array)for(var k in a)a.hasOwnProperty(k)&&f(this.sound,a[k]);else if(b.formats.length)for(var j in b.formats)b.formats.hasOwnProperty(j)&&f(this.sound,a+"."+b.formats[j]);
else f(this.sound,a);b.loop&&this.loop();b.autoplay&&(this.sound.autoplay="autoplay");this.sound.preload=!0===b.preload?"auto":!1===b.preload?"none":b.preload;this.setVolume(b.volume);buzz.sounds.push(this)}},group:function(a){function b(){for(var b=c(null,arguments),d=b.shift(),g=0;g<a.length;g++)a[g][d].apply(a[g],b)}function c(a,b){return a instanceof Array?a:Array.prototype.slice.call(b)}a=c(a,arguments);this.getSounds=function(){return a};this.add=function(b){for(var b=c(b,arguments),d=0;d<b.length;d++)a.push(b[d])};
this.remove=function(b){for(var b=c(b,arguments),d=0;d<b.length;d++)for(var g=0;g<a.length;g++)if(a[g]==b[d]){delete a[g];break}};this.load=function(){b("load");return this};this.play=function(){b("play");return this};this.togglePlay=function(){b("togglePlay");return this};this.pause=function(a){b("pause",a);return this};this.stop=function(){b("stop");return this};this.mute=function(){b("mute");return this};this.unmute=function(){b("unmute");return this};this.toggleMute=function(){b("toggleMute");
return this};this.setVolume=function(a){b("setVolume",a);return this};this.increaseVolume=function(a){b("increaseVolume",a);return this};this.decreaseVolume=function(a){b("decreaseVolume",a);return this};this.loop=function(){b("loop");return this};this.unloop=function(){b("unloop");return this};this.setTime=function(a){b("setTime",a);return this};this.setduration=function(a){b("setduration",a);return this};this.set=function(a,c){b("set",a,c);return this};this.bind=function(a,c){b("bind",a,c);return this};
this.unbind=function(a){b("unbind",a);return this};this.bindOnce=function(a,c){b("bindOnce",a,c);return this};this.trigger=function(a){b("trigger",a);return this};this.fade=function(a,c,g,m){b("fade",a,c,g,m);return this};this.fadeIn=function(a,c){b("fadeIn",a,c);return this};this.fadeOut=function(a,c){b("fadeOut",a,c);return this}},all:function(){return new buzz.group(buzz.sounds)},isSupported:function(){return!!buzz.el.canPlayType},isOGGSupported:function(){return!!buzz.el.canPlayType&&buzz.el.canPlayType('audio/ogg; codecs="vorbis"')},
isWAVSupported:function(){return!!buzz.el.canPlayType&&buzz.el.canPlayType('audio/wav; codecs="1"')},isMP3Supported:function(){return!!buzz.el.canPlayType&&buzz.el.canPlayType("audio/mpeg;")},isAACSupported:function(){return!!buzz.el.canPlayType&&(buzz.el.canPlayType("audio/x-m4a;")||buzz.el.canPlayType("audio/aac;"))},toTimer:function(a,b){var c,f,d;c=Math.floor(a/3600);c=isNaN(c)?"--":10<=c?c:"0"+c;f=b?Math.floor(a/60%60):Math.floor(a/60);f=isNaN(f)?"--":10<=f?f:"0"+f;d=Math.floor(a%60);d=isNaN(d)?
"--":10<=d?d:"0"+d;return b?c+":"+f+":"+d:f+":"+d},fromTimer:function(a){var b=a.toString().split(":");b&&3==b.length&&(a=3600*parseInt(b[0],10)+60*parseInt(b[1],10)+parseInt(b[2],10));b&&2==b.length&&(a=60*parseInt(b[0],10)+parseInt(b[1],10));return a},toPercent:function(a,b,c){c=Math.pow(10,c||0);return Math.round(100*a/b*c)/c},fromPercent:function(a,b,c){c=Math.pow(10,c||0);return Math.round(b/100*a*c)/c}},createReceiver=function(){return{handlePencilMessage:function(a,b){var c=a.readTick(),f=
a.readBool(),d=b.pen;f&&(d.pos=a.readPos());for(;a.at<a.data.length;){var f=a.readPos(),g=new TimedSegment(d.pos.x,d.pos.y,f.x,f.y,c);d.seg.push(g);c++;d.pos=f}}}};ByteMessage=function(a,b){this.data=a;this.at=b};ByteMessage.prototype.readPos=function(){var a=this.data.charCodeAt(this.at++),b=this.data.charCodeAt(this.at++),c=this.data.charCodeAt(this.at++);return new Vector(a|(b&15)<<7,b>>4|c<<3)};
ByteMessage.prototype.readTick=function(){var a=this.data.charCodeAt(this.at++),b=this.data.charCodeAt(this.at++),c=this.data.charCodeAt(this.at++);return a|b<<7|c<<14};ByteMessage.prototype.readBool=function(){return this.data.charCodeAt(this.at++)};
function createDomManager(a){function b(){x.disabled=!1;x.innerHTML="Start Game";e=null}function c(a){for(var b=["disconnect","stop","back"],c=0;c<b.length;c++)document.getElementById(b[c]).style.display=a==b[c]?"block":"none"}function f(a){for(var b=["connectionContainer","gameListContainer","editor","waitContainer","gameContainer"],c=0;c<b.length;c++){var e=document.getElementById(b[c]);a==b[c]?e.classList.add("contentVisible"):e.classList.remove("contentVisible")}}function d(){var a=document.getElementById("chatContainer"),
b=document.getElementById("options"),c=document.getElementById("playerListContainer"),e=document.getElementById("chatForm"),d=document.getElementById("gameTitle");a.style.maxHeight=document.body.clientHeight-b.offsetHeight-e.offsetHeight-c.offsetHeight-d.offsetHeight-30+"px"}function g(){"editing"==a.state?a.editor.resize():("playing"==a.state||"watching"==a.state||"ended"==a.state||"countdown"==a.state)&&a.resize();d()}function m(){clearTimeout(C);C=setTimeout(g,resizeDelay)}function i(v,c){return function(){if(!(a.host!=
a.localPlayer||"waiting"!=a.state)&&!(c&&null==y))window.clearTimeout(y),y=window.setTimeout(function(){a.sendParams();y=null},v),x.disabled=!0,x.innerHTML="Please wait",null!==e&&window.clearTimeout(e),e=window.setTimeout(b,unlockInterval+v)}}function h(){var b=document.getElementById("playername").value;j.setSidebarVisibility(!0);"string"!=typeof b||1>b.length||b.length>maxNameLength?j.gameMessage("Enter a cool nickname please (no longer than "+maxNameLength+" chars)"):(setCookie("playerName",a.localPlayer.playerName=
b,30),a.connect(serverURL,"game-protocol",function(){a.joinLobby(a.localPlayer)}),r.disabled=!0,r.innerHTML="Connecting...")}function k(){var b=parseInt(document.getElementById("maxplayers").value),c=parseInt(document.getElementById("minplayers").value);8<b||1>b||8<c||1>c||c>b?j.gameMessage("Min/ maxplayers unacceptable!"):(setCookie("maxPlayers",b,30),setCookie("minPlayers",c,30),p.disabled=!0,a.sendMsg("requestGame",{minPlayers:c,maxPlayers:b}))}function j(){}var l,o,q,s,t,r,p,u,n,E,D,x,w,z,F,A,
C=null,y=null,e=null;setKickLinksVisibility=function(a){for(var b=l.getElementsByTagName("a"),c=0;c<b.length;c++)b[c].className=a?"close":"close hidden"};j.onload=function(){l=document.getElementById("playerList").lastChild;o=document.getElementById("gameList").lastChild;q=document.getElementById("chat");s=document.getElementById("sidebar");t=document.getElementById("status");r=document.getElementById("connect");p=document.getElementById("automatch");u=document.getElementById("createGame");n=document.getElementById("stop");
E=document.getElementById("disconnect");D=document.getElementById("back");x=document.getElementById("startGame");w=document.getElementById("hostContainer");F=document.getElementById("addComputerHard");z=document.getElementById("addComputerEasy");A=document.getElementById("nonhostContainer");displayDebugStatus&&(t.style.display="block");window.onresize=m;if(touchDevice||alwaysHideSidebar){var b=document.getElementById("menuButton");b.style.display="block";b.addEventListener("click",function(b){a.toggleSidebar();
b.preventDefault();b.stopPropagation()},!0)}if("WebSocket"in window||"MozWebSocket"in window)document.getElementById("noWebsocket").style.display="none";for(var b=document.getElementById("details").getElementsByTagName("input"),c=0;c<b.length;c++)"text"==b[c].type||"number"==b[c].type?(b[c].addEventListener("input",i(paramInputInterval,!1),!1),b[c].addEventListener("change",i(paramUpdateInterval,!0),!1)):b[c].addEventListener("change",i(paramUpdateInterval,!1),!1);document.getElementById("chatForm").addEventListener("submit",
function(b){var c=q.value;q.value="";if(!(c.length<1)){a.sendMsg("chat",{message:c});j.printChat(a.localPlayer,c);b.preventDefault()}},!1);r.addEventListener("click",h,!1);p.addEventListener("click",k,!1);x.addEventListener("click",function(){a.sendStartGame();x.disabled=true},!1);u.addEventListener("click",function(){a.sendMsg("createGame",{});u.disabled=true},!1);n.addEventListener("click",function(){a.leaveGame();n.disabled=true},!1);E.addEventListener("click",function(){a.disconnect()},!1);D.addEventListener("click",
function(){a.setGameState("waiting");a.backToGameLobby()},!1);z.addEventListener("click",function(){a.addComputer("easy")},!1);F.addEventListener("click",function(){a.addComputer("hard")},!1);b=getCookie("minPlayers");null!=b&&(document.getElementById("minplayers").value=b);b=getCookie("maxPlayers");null!=b&&(document.getElementById("maxplayers").value=b);b=getCookie("playerName");-1!=location.href.indexOf("C:/Dropbox")&&(b="piet",document.getElementById("sound").checked=!1,a.audioController.enableSound=
!1,document.getElementById("minplayers").value=1);null!=b&&""!=b&&(document.getElementById("playername").value=b,h())};j.setDebugMessage=function(a){t.innerHTML=a};j.setWaitMessage=function(a){A.innerHTML=a?customGameWaitMessage:autoMatchWaitMessage};j.newHost=function(a){w.style.display=a?"block":"none";A.style.display=a?"none":"block";for(var b=document.getElementById("details").getElementsByTagName("input"),c=0;c<b.length;c++)b[c].disabled=!a;setKickLinksVisibility(a&&("waiting"==this.state||"ended"==
this.state||"editing"==this.state))};j.updateTitle=function(a){document.getElementById("gameTitle").innerHTML=a};j.appendPlayerList=function(b){var c=document.createElement("tr"),e=document.createElement("td"),H=document.createElement("span"),f=document.createElement("a"),h=document.createElement("td"),g=document.createElement("td");H.innerHTML=b.playerName;H.className="noverflow";b.row=c;f.className=a.host==a.localPlayer?"close":"close hidden";f.innerHTML="x";f.addEventListener("click",function(){a.requestKick(parseInt(b.id))});
l.appendChild(c);b!=a.localPlayer&&e.appendChild(f);e.appendChild(H);c.appendChild(e);c.appendChild(h);c.appendChild(g);b.updateRow();d()};j.clearPlayerList=function(){for(;l.hasChildNodes();)l.removeChild(l.firstChild);d()};j.splicePlayerList=function(a){l.removeChild(a.row);d()};j.sortPlayerList=function(){for(var a=l.getElementsByTagName("tr"),b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];b.sort(function(a,b){var c=parseInt(a.lastChild.innerHTML),v=parseInt(b.lastChild.innerHTML);return c==v?
0:c>v?-1:1});for(c=1;c<a.length;c++)b[c]!=l.lastChild&&(l.removeChild(b[c]),l.appendChild(b[c]))};j.buildGameList=function(a){for(var b=[];o.hasChildNodes();)o.removeChild(o.firstChild);document.getElementById("noGames").style.display="block";for(var c=0;c<a.length;c++)"below"!=startedGamesDisplay&&"started"==a[c].state?b.push(a[c]):this.appendGameList(a[c]);if("below"==startedGamesDisplay)for(c=0;c<b.length;c++)this.appendGameList(b[c])};j.appendGameList=function(b){document.getElementById("noGames").style.display=
"none";var c=document.createElement("tr");c.id="game"+b.id;var e=document.createElement("td");e.innerHTML=b.id;c.appendChild(e);e=document.createElement("td");e.innerHTML=b.type;c.appendChild(e);var e=document.createElement("td"),d=document.createElement("span");d.innerHTML=void 0!=b.host?b.host:"-";d.className="noverflow";e.appendChild(d);c.appendChild(e);e=document.createElement("td");e.innerHTML=b.state;c.appendChild(e);e=document.createElement("td");e.innerHTML=b.n+"/"+("custom"==b.type?b.nmax:
b.nmin);c.appendChild(e);d=document.createElement("button");d.innerHTML="Join";d.disabled="lobby"!=b.state;d.addEventListener("click",function(){a.joinGame(b.id)});e=document.createElement("td");e.appendChild(d);c.appendChild(e);o.appendChild(c)};j.setGameState=function(b,B){if("new"==B||"new"==b){var e="new"==B?"none":"block";document.getElementById("playerListContainer").style.display=e;document.getElementById("gameTitle").style.display=e;document.getElementById("chatForm").style.display=e}if("waiting"==
B||"lobby"==B||"new"==B)document.getElementById("gameTitle").className="",document.getElementById("goalDisplay").style.display="none";switch(B){case "lobby":c("disconnect");f("gameListContainer");u.disabled=p.disabled=!1;break;case "editing":f("editor");break;case "countdown":f("gameContainer");setKickLinksVisibility(!1);document.getElementById("gameTitle").className="leftSide";document.getElementById("goalDisplay").style.display="block";break;case "waiting":c("stop");f("waitContainer");x.disabled=
!1;n.disabled=!1;break;case "playing":c("stop");break;case "ended":this.setSidebarVisibility(!0)&&a.resize();setKickLinksVisibility(a.host==a.localPlayer);"custom"==a.type&&c("back");break;case "new":f("connectionContainer"),c("nothing"),r.disabled=!1,r.innerHTML="Connect"}};j.focusChat=function(){touchDevice||q.focus()};j.gameMessage=function(a){var b=document.getElementById("messages"),c=document.createElement("li");c.innerHTML=a;c.className="gameMessage";b.insertBefore(c,b.firstChild)};j.printChat=
function(a,b){var c=escapeString(b),e=document.getElementById("messages"),d=document.createElement("li"),f=document.createElement("span");f.innerHTML=a.isLocal?"me":a.playerName;f.className="player";d.innerHTML=c;d.className="chatMessage";d.insertBefore(f,d.firstChild);e.insertBefore(d,e.firstChild)};j.setSidebarVisibility=function(a){if(a==s.classList.contains("visible"))return!1;s.classList.toggle("visible");document.getElementById("menuButton").innerHTML=a?"&lt;":"&gt;";for(var a=document.getElementsByTagName("article"),
b=0;b<a.length;b++)a[b].classList.toggle("translated");return!0};j.sidebarWidth=function(){return s.classList.contains("visible")?sidebarWidth:0};j.toggleSidebar=function(){this.setSidebarVisibility(!s.classList.contains("visible"));a.resize()};j.findPos=function(a){var b=curtop=0;if(a.offsetParent){do b+=a.offsetLeft,curtop+=a.offsetTop;while(a=a.offsetParent)}return new Vector(b,curtop)};return j}function MouseState(){this.down=!1;this.out=!0}
function createEditor(a){function b(b,c,h){var g="eraser"==m?eraserStepTime:editorStepTime,i=!1,j=!1;null!=c&&(h.pos=a.getGamePos(c),c.preventDefault&&"up"!=b&&c.preventDefault());switch(b){case "down":h.down=!0;h.out=!1;i=!0;break;case "over":h.out=!1;h.down&&f("eraser","pencil")&&(i=!0);break;case "up":h.down&&!h.out&&(j=!0);h.down=!1;break;case "out":h.out=!0;h.down&&f("eraser","pencil")&&(j=!0);break;case "move":h.down&&(f("eraser","pencil")&&Date.now()-h.startTime>g)&&(j=!0)}if(j&&(h.pos.x!=
h.start.x||h.pos.y!=h.start.y)){b=new EditorSegment(h.start.x,h.start.y,h.pos.x,h.pos.y,m);switch(m){case "playerStart":b.angle=getAngle(b.x2-b.x1,b.y2-b.y1);break;case "teleport":if(!(c=getLength(b.x2-b.x1,b.y2-b.y1)<minTeleportSize)){a:{c=Array(maxTeleports);g=-1;for(i=0;i<maxTeleports;i++)c[i]=0;for(i in n.segments)j=n.segments[i],"teleport"==j.mode&&c[j.teleportId]++;for(i=0;i<maxTeleports;i++){if(1==c[i]){c=i;break a}0==c[i]&&-1==g&&(g=i)}c=g}c=-1==(b.teleportId=c)}if(c)return;break;case "eraser":c=
!1;for(g=0;g<n.segments.length;g++)-1!=segmentCollision(n.segments[g],b)&&(n.segments.splice(g--,1),c=!0,n.mapChanged=!0);c&&n.resize()}f("eraser")||(n.segments.push(b),n.mapChanged=!0,d(b));i=!0}i&&(h.start=h.pos,h.startTime=Date.now())}function c(){0<n.segments.length&&(n.segments.pop(),n.resize())}function f(){for(var a=0;a<arguments.length;a++)if(m==arguments[a])return!0;return!1}function d(a){a.x1==a.x2&&a.y1==a.y2||("playerStart"==a.mode?(h.drawIndicatorArrow(l,a.x1,a.y1,a.angle,playerColors[0]),
h.setLineColor(l,mapSegmentColor,1)):"teleport"==a.mode?(h.drawTeleport(l,a),h.setLineColor(l,mapSegmentColor,1)):(l.beginPath(),l.moveTo(a.x1,a.y1),l.lineTo(a.x2,a.y2),l.stroke()))}var g=new MouseState,m="pencil",i=a.domManager,h=a.canvasManager,k,j,l,o,q,s,t,r,p,u,n={mapChanged:!1,segments:[],resize:function(){a.calcScale(document.getElementById("editorControls").offsetHeight+1);var b=Math.round(a.scaleX*a.width),c=Math.round(a.scaleY*a.height),f=b!=j.width;j.width=b;j.height=c;l.scale(a.scaleX,
a.scaleY);l.lineWidth=3;h.setLineColor(l,mapSegmentColor,1);l.lineCap="round";for(b=0;b<this.segments.length;b++)d(this.segments[b]);f&&(g.down=!1)},load:function(b){try{var c=JSON.parse(b)}catch(d){a.gameMessage("JSON parse exception!")}this.segments=c;this.resize();this.mapChanged=!0},handleKeyEvent:function(a){if("block"!=q.style.display)switch(String.fromCharCode(a.keyCode)){case "U":c();break;case "P":case "1":simulateClick(s);break;case "L":case "2":simulateClick(t);break;case "S":case "3":simulateClick(p);
break;case "T":case "4":simulateClick(u);break;case "E":case "5":simulateClick(r);break;default:return}else if(27==a.keyCode)closeModal();else return;a.preventDefault()},onload:function(){function d(){w.style.display="none";q.style.display="none"}function f(a){for(var b=a.target,c=b.parentNode.getElementsByTagName("a"),v=0;v<c.length;v++)c[v].className="btn";b.className="btn active";m=a.target.mode}function h(a){return function(c){for(var v=0;v<c.changedTouches.length;v++){var e=c.changedTouches[v];
b(a,e,e)}c.preventDefault()}}var w=document.getElementById("overlay"),z=document.getElementById("modalHeader"),F=document.getElementById("editorReset"),A=document.getElementById("editorCopy"),C=document.getElementById("editorLoad"),y=document.getElementById("editorUndo"),e=document.getElementById("editorStart"),v=document.getElementById("editorDone"),B=document.getElementById("modalClose"),G=document.getElementById("modalOk");q=document.getElementById("mapLoader");s=document.getElementById("editorPencil");
t=document.getElementById("editorLine");r=document.getElementById("editorEraser");p=document.getElementById("editorPlayerStart");u=document.getElementById("editorTeleport");j=document.getElementById("editorCanvas");document.getElementById("editor");k=document.getElementById("editorTextField");l=j.getContext("2d");j.width=j.height=0;s.className="btn active";s.mode="pencil";t.mode="line";r.mode="eraser";p.mode="playerStart";u.mode="teleport";j.addEventListener("mousedown",function(a){b("down",a,g)},
!1);j.addEventListener("mousemove",function(a){b("move",a,g)},!1);window.addEventListener("mouseup",function(a){b("up",a,g)},!1);j.addEventListener("mouseout",function(a){b("out",a,g)},!1);j.addEventListener("mouseover",function(a){b("over",a,g)},!1);F.addEventListener("click",function(){n.segments=[];n.mapChanged=!0;n.resize()},!1);A.addEventListener("click",function(){z.innerHTML="Store map";w.style.display="block";q.style.display="block";G.innerHTML="Done";k.value=JSON.stringify(n.segments)},!1);
C.addEventListener("click",function(){z.innerHTML="Load map";w.style.display="block";q.style.display="block";G.innerHTML="Load Map"},!1);G.addEventListener("click",function(){"Load Map"==G.innerHTML&&n.load(k.value);d()});y.addEventListener("click",c,!1);e.addEventListener("click",function(){a.setGameState("editing");i.findPos(j);n.resize();o=window.setInterval(function(){b("move",null,g)},editorStepTime);a.noMapSent&&0<n.segments.length&&(a.noMapSent=!1,n.mapChanged=!0);window.scroll(document.body.offsetWidth,
0)},!1);v.addEventListener("click",function(){a.setGameState("waiting");window.clearInterval(o);j.height=j.width=0},!1);w.addEventListener("click",d,!1);B.addEventListener("click",d,!1);s.addEventListener("click",f,!1);t.addEventListener("click",f,!1);r.addEventListener("click",f,!1);p.addEventListener("click",f,!1);u.addEventListener("click",f,!1);j.addEventListener("touchstart",h("down"),!1);j.addEventListener("touchmove",h("move"),!1);j.addEventListener("touchend",h("up"),!1);j.addEventListener("touchcancel",
h("up"),!1)}};return n}var enableSound=!0,joinedLink=!1,keyCodeLeft=37,keyCodeRight=39,serverURL="ws://diekurve.net:7681";-1!=location.href.indexOf("7681")?serverURL=location.href.replace("http","ws"):-1!=location.href.indexOf("C:/Dropbox")&&(serverURL="ws://localhost:7681");
var vSync=!0,maxCanvasStretch=1.1,holeAlpha=0.2,lineWidth=3,lineCapStyle="round",canvasMinimumWidth=150,crossSize=12,crossLineWidth=2,crossColor=[0,0,0],teleportLineWidth=2,rewardShowLength=1E3,rewardMaxTransitionLength=1E3,rewardOffsetY=8,rewardWidth=23,rewardHeight=18,maxHiddenRewards=20,startedGamesDisplay="below",indicatorLength=15,indicatorArrowLength=8,indicatorArrowOffset=2,indicatorFont=20,sidebarWidth=301,dashLength=5,dashSpacing=5,syncTries=2,syncDelays=50,tickTockDifference=2,backupStates=
[Infinity,40,10,0],resizeDelay=200,paramUpdateInterval=500,paramInputInterval=2E3,customGameWaitMessage="Waiting for host to start the game..",autoMatchWaitMessage="Waiting for more players..",touchDevice="createTouch"in document,steerBoxSize=0.15,pencilTreshold=20,inkBufferTicks=5,pencilAlpha=0.2,emulateTouch=!1,ultraVerbose=!1,simulatedPing=0,extraGameStartTimeDifference=0,acceptGameTimeAdjustments=!0,jsProfiling=!1,simulateCPUlag=!1,displayDebugStatus=!1,fpsInterval=500,debugRewards=!1,alwaysHideSidebar=
!1,debugComputers=0,debugMap="",debugZeroLengthSegs=!1,autoStart=!1,maxNameLength=20,modeModified=0,modeTickUpdate=1,modePencil=2,modeJson=3,modeOther=7,modeSetMap=15,unlockInterval=0,minTeleportSize=15,maxTeleports=8,epsilon=1.0E-4,serverDalay=200,editorStepTime=75,eraserStepTime=50,mapSegmentColor=[96,96,96],canvasColor="#E0E0E0",playerColors=[[237,28,36],[63,72,204],[43,177,76],[0,0,0],[185,122,87],[163,73,164],[0,162,232],[136,0,21]];window.onload=function(){rareNaam.onload()};
var rareNaam=function(){function a(a){var b=a.charCodeAt(0),c=b&7;if(c==modeJson)return!1;if(c==modeModified){var c=a.charCodeAt(1),d=a.charCodeAt(2),a=a.charCodeAt(3),b=(b&120)>>3|c<<4|(d&15)<<11;e.correctionTick=Math.min(e.localPlayer.inputs[b].tick+=(d&112)>>4|a<<3,e.correctionTick);return!0}if(c==modeTickUpdate)return c=a.charCodeAt(1),d=a.charCodeAt(2),a=j[(b&56)>>3],a.lastInputTick+=(b&64)>>6|(127&c)<<1|(127&d)<<8,!0;if(c==modeOther)switch(c=b,c){case modeSetMap:d=new ByteMessage(a,3);e.mapSegments.length=
0;for(e.mapTeleports.length=0;;){c=a.charCodeAt(d.at++);if(0==c)break;e.mapTeleports.push(e.getTeleport(c&31,d.readPos(),d.readPos(),d.readPos(),d.readPos()))}for(;d.at<d.data.length;)b=d.readPos(),c=d.readPos(),e.mapSegments.push(new Segment(b.x,b.y,c.x,c.y));return!0}switch(c){case modePencil:return d=new ByteMessage(a,1),a=j[(b&56)>>3],o.handlePencilMessage(d,a),!0}}function b(a){var b=a.charCodeAt(0),c=a.charCodeAt(1),d=(b&8)>>3,a=j[b&7];var f=a.lastInputTurn,d=(0==f||1==f)&&0==d?-1:(0==f||-1==
f)&&1==d?1:0;b=a.lastInputTick+=(b&112)>>4|c<<3;a.lastInputTurn=d;a.inputs.push(new Turn(d,b,0,0,!1));b<=Math.floor(y)&&(e.correctionTick=Math.min(e.correctionTick,b))}function c(c){if(2==c.data.length)return b(c.data);if(!a(c.data)){try{var d=JSON.parse(c.data)}catch(f){e.domManager.gameMessage("JSON parse exception!")}ultraVerbose&&"segments"!=d.mode&&e.domManager.gameMessage("Received data: "+c.data);switch(d.mode){case "acceptUser":e.localPlayer.id=d.playerId;e.tickLength=d.tickLength;e.pencil.setParameters(d);
autoStart&&e.createGame();break;case "kickNotification":e.domManager.gameMessage("You were kicked from the game");break;case "joinedGame":k.length=0;e.domManager.clearPlayerList();e.host=null;e.type=d.type;e.setGameState("lobby"==d.type?"lobby":"waiting");e.mapSegments.length=0;e.mapTeleports.length=0;e.noMapSent=!0;j[d.index]=e.localPlayer;e.localPlayer.index=d.index;e.addPlayer(e.localPlayer);if("lobby"==d.type){e.domManager.updateTitle("Lobby");var g=window.location.href.indexOf("?game=",0);!joinedLink&&
-1!=g&&(e.joinGame(parseInt(window.location.href.substr(g+6))),joinedLink=!0)}else e.domManager.setWaitMessage("custom"==d.type);"custom"!=d.type&&e.setHost(null);break;case "gameParameters":e.setParams(d);break;case "newPlayer":g=new Player(e,!1);g.id=d.playerId;j[d.index]=g;g.index=d.index;g.playerName=escapeString(d.playerName);e.addPlayer(g);e.audioController.playSound("newPlayer");break;case "startGame":g=d.startTime-x-p+extraGameStartTimeDifference-Date.now();"ended"==e.state&&e.backToGameLobby();
document.getElementById("goalDisplay").innerHTML="Goal: "+d.goal+" points";g>C?r=window.setTimeout(function(){e.start(d.startPositions,d.startTime)},g-C):e.start(d.startPositions,d.startTime);break;case "adjustGameTime":acceptGameTimeAdjustments?(D-=d.forward,p+=d.forward,z++,e.displayDebugStatus()):e.domManager.gameMessage("Game time adjustment of "+d.forward+" msec rejected");break;case "playerLeft":c=e.getPlayer(d.playerId);if("lobby"!=e.state||"normal"!=d.reason)e.domManager.gameMessage(c.playerName+
" left the game"+("normal"==d.reason?"":" ("+d.reason+")"));e.removePlayer(c);e.audioController.playSound("playerLeft");break;case "playerDied":c=e.getPlayer(d.playerId);c.finalSteer(d);c.status="dead";c.updateRow();c==e.localPlayer&&("ondeath"==e.pencilMode?e.pencil.enable(d.tick):"off"==e.pencilMode&&e.setGameState("watching"),e.audioController.playSound("localDeath"));e.displayRewards(d.reward);for(g in k)c=k[g],"alive"==c.status&&(c.points+=d.reward,c.updateRow());e.domManager.sortPlayerList();
break;case "endRound":window.clearTimeout(r);document.getElementById("inkIndicator").style.display="none";for(g=e.maxHiddenRewards;g<i.length;g++)q.removeChild(i.pop());y=e.tick=Math.max(e.tick,d.finalTick);e.correctionTick=Math.min(e.correctionTick,d.finalTick);e.revertBackup();c=-1!=d.winnerId?e.getPlayer(d.winnerId):null;g=null!=c?c.playerName+" won":"draw!";e.setGameState("countdown");e.domManager.gameMessage("Round ended: "+g);break;case "endGame":e.setGameState("ended");window.clearTimeout(r);
g=e.getPlayer(d.winnerId);e.domManager.gameMessage("Game over: "+g.playerName+" won!");c=document.getElementById("winAnnouncer");c.innerHTML=g.playerName+" won!";c.style.display="inline-block";g.isLocal&&e.audioController.playSound("localWin");jsProfiling&&console.profileEnd();break;case "time":m(d.time);break;case "chat":e.audioController.playSound("chat");e.domManager.printChat(e.getPlayer(d.playerId),d.message);break;case "newGame":e.domManager.appendGameList(d);break;case "gameList":e.domManager.buildGameList(d.games);
break;case "segments":e.canvasManager.drawDebugSegments(e.baseContext,d.segments);h=h.concat(d.segments);break;case "stopSpamming":e.domManager.gameMessage("You are flooding the chat. Your latest message has been blocked");break;case "setHost":e.setHost(e.getPlayer(d.playerId));autoStart&&e.sendStartGame();break;case "joinFailed":c="game already started";"notFound"==d.reason?c="game not found":"full"==d.reason?c="game is full":"kicked"==d.reason&&(c="you are banned for another "+d.timer+" milliseconds");
e.domManager.gameMessage("Could not join game: "+c);"started"==d.reason?document.getElementById("game"+d.id).getElementsByTagName("button")[0].disabled=!0:"notFound"==d.reason&&(g=document.getElementById("game"+d.id),null!=g&&g.parentNode.removeChild(g),e.gameList.hasChildNodes()||(document.getElementById("noGames").style.display="block"));break;default:e.domManager.gameMessage("Unknown mode "+d.mode+"!")}}}function f(){e.baseContext.drawImage(canvases[0],0,0,e.width,e.height);e.audioController.playSound("gameStart");
e.setGameState("playing");e.sendMsg("enableInput",{});d()}function d(){if(!("playing"!=e.state&&"watching"!=e.state)){var a=(Date.now()-D)/e.tickLength,b=backupStates.length-1;if(displayDebugStatus){var c=e.tickLength*(e.tick-s);c>=fpsInterval&&(fps=1E3*t/c,s=e.tick,t=0,e.displayDebugStatus());t++}for(;e.tick<a;){var c=Math.floor(e.tick+1),f=e.tick==Math.floor(e.tick);if(f&&simulateCPUlag&&199==e.tick%200)for(var g=Date.now();400>Date.now()-g;);e.revertBackup();if(f)for(var h=0;h<b;h++)e.updateContext(h,
!0);e.updateContext(b,!1);if(f)for(h in e.pencil.doTick(),k)k[h].pen.doTick();e.tick=Math.min(c,a);e.correctionTick=Math.ceil(e.tick);y=Math.max(0,e.tick-tickTockDifference)}vSync?requestAnimFrame(d):setTimeout(d,0)}}function g(){u=Date.now();e.sendMsg("getTime",{})}function m(a){-1==w&&(p=0,n=9999,w=E=0);var b=(Date.now()-u)/2;b<n&&(n=b,x=a+b-Date.now());b>E?(p+=E,E=p/(syncTries-1)):p+=b/(syncTries-1);++w<syncTries?window.setTimeout(g,w*syncDelays):(e.domManager.gameMessage("Your current ping is "+
p+" msec"),ultraVerbose&&e.domManager.gameMessage("Synced with maximum error of "+n+" msec"),w=-1)}var i=[],h=[],k=[],j=Array(8),l,o,q,s=0,t=0,r=null,p=0,u=0,n=0,E=0,D=0,x=-1,w=-1,z=0,F=0,A=0,C=0,y=0,e=function(){this.state;this.type="custom";this.scaleX=this.scaleY=0;this.torus=this.noMapSent=!1;this.holeSize=this.holeFreq=this.tick=this.correctionTick=this.velocity=this.height=this.width=0;this.pencilMode="off";this.turnSpeed=1.5;this.host=null;this.ticklength=0;this.crossQueue;this.mapSegments;
this.mapTeleports;this.baseContext;this.contexts;this.mouse;this.localPlayer;this.audioController;this.editor;this.pencil;this.domManager;this.canvasManager};e.onload=function(){var a=document.getElementById("baseCanvas");q=document.getElementById("canvasContainer");this.mouse=new Vector(0,0);this.crossQueue=[];this.mapSegments=[];this.mapTeleports=[];this.baseContext=a.getContext("2d");this.state="new";canvases=Array(backupStates.length);this.contexts=Array(backupStates.length);for(var b=0;b<backupStates.length-
1;b++)canvases[b]=document.createElement("canvas"),this.contexts[b]=canvases[b].getContext("2d");canvases[backupStates.length-1]=a;this.contexts[backupStates.length-1]=this.baseContext;this.audioController=new AudioController;this.domManager=createDomManager(this);this.canvasManager=createCanvasManager(this);this.pencil=createPencil(this);this.editor=createEditor(this);this.localPlayer=new Player(this,!0);o=createReceiver();this.audioController.onload();this.pencil.onload();this.editor.onload();this.domManager.onload()};
e.getPlayer=function(a){return k[a]};e.connect=function(a,b,d){if("MozWebSocket"in window)l=new MozWebSocket(a,b);else if("WebSocket"in window)l=new WebSocket(a,b);else return;try{l.onopen=function(){e.domManager.gameMessage("Connected to server");e.connected=!0;g();d()},l.onmessage=function(a){0<simulatedPing?window.setTimeout(function(){c(a)},simulatedPing):c(a)},l.onclose=function(){e.connected?(e.domManager.gameMessage("Disconnected from server"),e.connected=!1):e.domManager.gameMessage("Could not connect to server");
e.setGameState("new")}}catch(f){e.domManager.gameMessage("Websocket exception! "+f.name+": "+f.message)}};e.disconnect=function(){l.close(1E3)};e.leaveGame=function(){this.sendMsg("leaveGame",{});window.clearTimeout(r)};e.addComputer=function(a){this.sendMsg("addComputer",{type:a})};e.joinGame=function(a){this.sendMsg("join",{id:a})};e.joinLobby=function(a){this.sendMsg("joinLobby",{playerName:a.playerName});a.playerName=escapeString(a.playerName)};e.sendStartGame=function(){var a={};null!=debugMap&&
""!=debugMap&&this.editor.load(debugMap);this.editor.mapChanged&&(a.segments=this.editor.segments,this.editor.mapChanged=!1);if(0<debugComputers)for(var b=0;b<debugComputers;b++)this.addComputer();this.sendMsg("startGame",a)};e.requestKick=function(a){this.sendMsg("kick",{playerId:a})};e.getCollision=function(a,b,c,d){var e=new Segment(a,b,c,d),f,g=1,h=null,i;for(i in this.mapTeleports){var j=this.mapTeleports[i];Math.max(a,c)<j.left||(Math.min(a,c)>j.right||Math.max(b,d)<j.top||Math.min(b,d)>j.bottom)||
(f=segmentCollision(j,e),-1!=f&&f<g&&(g=f,h=j))}return null!=h?(f=g,a=(1-f)*a+f*c,b=(1-f)*b+f*d,d=h.tall?b-h.y1:a-h.x1,new Collision(!0,a,b,h.destX+d*h.dx,h.destY+d*h.dy,h.extraAngle)):null};e.setGameState=function(a){this.domManager.setGameState(e.state,a);this.state=a};e.getTeleport=function(a,b,c,d,e){var f=c.x-b.x,h=c.y-b.y,g=e.x-d.x,e=e.y-d.y,a=new Teleporter(b.x,b.y,c.x,c.y,a);a.tall=Math.abs(h)>Math.abs(f);a.dx=g/(a.tall?h:f);a.dy=e/(a.tall?h:f);a.extraAngle=getAngle(g,e)-getAngle(f,h);a.destX=
d.x;a.destY=d.y;return a};e.removePlayer=function(a){delete k[a.id];"waiting"==this.state||"lobby"==this.state||"editing"==this.state||"left"==a.status||"ended"==this.state&&"ready"==a.status?this.domManager.splicePlayerList(a):(a.id+="_left",k[a.id]=a,a.status="left",a.updateRow())};e.setHost=function(a){if(null!=this.host&&(this.host.isHost=!1,"waiting"==this.state||"editing"==this.state))this.host.status="ready",this.host.updateRow();if(null!=a){if(this.host=a,this.host.isHost=!0,"waiting"==this.state||
"editing"==this.state)this.host.status="host",this.host.updateRow()}else this.host=null;this.domManager.newHost(this.host==this.localPlayer)};e.setParams=function(a){this.width=a.w;this.height=a.h;C=a.countdown;this.velocity=a.v;this.turnSpeed=a.ts;this.holeSize=a.hsize;this.holeFreq=a.hfreq;this.pencilMode=a.pencilmode;this.torus=0!=a.torus;"off"!=this.pencilMode&&this.pencil.setParameters(a);"editing"==this.state&&this.editor.resize();if("lobby"!=a.type){document.getElementById("nmin").value=a.nmin;
document.getElementById("nmax").value=a.nmax;document.getElementById("width").value=this.width;document.getElementById("height").value=this.height;document.getElementById("velocity").value=this.velocity;document.getElementById("turnSpeed").value=this.turnSpeed;document.getElementById("holeSize").value=this.holeSize;document.getElementById("holeFreq").value=this.holeFreq;document.getElementById("goal").value=a.goal;document.getElementById("torus").checked=this.torus;document.getElementById("inkCapacity").value=
a.inkcap;document.getElementById("inkRegen").value=a.inkregen;document.getElementById("inkDelay").value=a.inkdelay;setPencilMode(a.pencilmode);this.domManager.updateTitle("Game "+a.id);var b=new String(window.location),c=b.indexOf("?",0);-1!=c&&(b=b.substr(0,c));b+="?game="+a.id;document.getElementById("friendInviter").innerHTML="Invite your friends by sending them this link: "+b}};e.sendMsg=function(a,b){b.mode=a;var c=JSON.stringify(b);0<simulatedPing?window.setTimeout(function(){l.send(c);ultraVerbose&&
GameMessage.domManager.gameMessage("Sending data: "+c)},simulatedPing):(l.send(c),ultraVerbose&&this.domManager.gameMessage("Sending data: "+c))};e.addPlayer=function(a){a.color=playerColors[a.index];a.segColor=getRGBstring(a.color);a.holeColor=getRGBAstring(a.color,holeAlpha);a.status="ready";a.points=0;a.isHost=!1;k[a.id]=a;this.domManager.appendPlayerList(a);a==this.localPlayer&&this.pencil.updateColor()};e.calcScale=function(a){var b=this.domManager.sidebarWidth(),b=Math.max(document.body.clientWidth-
b,canvasMinimumWidth)/this.width,a=(document.body.clientHeight-a)/this.height;this.scaleY=this.scaleX=Math.min(b,a);Math.max(this.scaleX/b,b/this.scaleX,this.scaleY/a,a/this.scaleY)<=maxCanvasStretch&&(this.scaleX=b,this.scaleY=a)};e.sendParams=function(){this.sendMsg("setParams",{goal:parseInt(document.getElementById("goal").value),v:parseInt(document.getElementById("velocity").value),w:parseInt(document.getElementById("width").value),h:parseInt(document.getElementById("height").value),ts:parseFloat(document.getElementById("turnSpeed").value),
hsize:parseInt(document.getElementById("holeSize").value),hfreq:parseInt(document.getElementById("holeFreq").value),pencilmode:getPencilMode(),nmax:parseInt(document.getElementById("nmax").value),torus:document.getElementById("torus").checked?1:0,inkcap:parseInt(document.getElementById("inkCapacity").value),inkregen:parseInt(document.getElementById("inkRegen").value),inkdelay:parseInt(document.getElementById("inkDelay").value)})};e.start=function(a,b){D=b-x-p+extraGameStartTimeDifference;this.setGameState("countdown");
var c=D-Date.now();e.correctionTick=0;e.tick=y=-1;F=z=A=0;fps=t=s=h.length=0;e.crossQueue.length=0;document.getElementById("winAnnouncer").style.display="none";e.pencil.reset();jsProfiling&&console.profile("canvas performance");this.audioController.playSound("countdown");for(var d=0;d<a.length;d++){var g=this.getPlayer(a[d].playerId);g.initialise(a[d].startX,a[d].startY,a[d].startAngle,a[d].holeStart)}"on"==this.pencilMode&&this.pencil.enable(0);for(d in k)g=k[d],"left"==g.status&&(g.finalTick=-1);
(alwaysHideSidebar||touchDevice)&&this.domManager.setSidebarVisibility(!1);this.resize();for(d=1;d<backupStates.length;d++)this.contexts[d].drawImage(canvases[0],0,0,this.width,this.height);for(d=0;d<a.length;d++)this.getPlayer(a[d].playerId).drawIndicator();r=window.setTimeout(f,c+this.tickLength);this.domManager.focusChat()};e.revertBackup=function(){var a=Math.ceil(this.tick);if(!(this.correctionTick>=a)){A++;this.displayDebugStatus();for(var b=backupStates.length-1;this.correctionTick<a-backupStates[b];b--);
for(var c in k){var d=k[c];d.states[b+1].copyState(d.states[b])}this.contexts[b+1].drawImage(canvases[b],0,0,this.width,this.height);this.correctionTick=a-backupStates[b+1];this.updateContext(b+1,!0);this.canvasManager.drawDebugSegments(this.baseContext,h);this.revertBackup()}};e.updateContext=function(a,b){for(var c in k){var d=k[c],e=d.isLocal?this.tick:y,e=e-backupStates[a];b&&(e=Math.floor(e));d.simulate(e,this.contexts[a],d.states[a])}this.drawCrosses(a)};e.drawCrosses=function(a){for(var b=
0,c=this.crossQueue.length/2;b<c;b++)this.canvasManager.drawCross(this.contexts[a],this.crossQueue[2*b],this.crossQueue[2*b+1]);this.crossQueue.length=0};e.createRewardNode=function(a,b){var c,d=0<i.length,e=rewardWidth,f=rewardHeight,h=a.states[backupStates.length-1];d?c=i.pop():(c=document.createElement("div"),c.className="reward");c.innerHTML="+"+b;var g=h.x*this.scaleX-e/2,g=Math.min(this.width*this.scaleX-e,Math.max(0,g)),e=h.y*this.scaleY-f-rewardOffsetY;0>e&&(e+=2*rewardOffsetY+f);c.style.left=
g+"px";c.style.top=e+"px";d?c.style.display="block":q.appendChild(c);return c};e.displayRewards=function(a){function b(){for(var a=0;a<d.length;a++)d[a].className="reward",d[a].style.display="none";i=i.concat(d)}function c(){for(var a=0;a<d.length;a++)d[a].classList.add("reward-hidden")}if(a){var d=[],e;for(e in k){var f=k[e];"alive"==f.status&&d.push(this.createRewardNode(f,a))}window.setTimeout(c,rewardShowLength);window.setTimeout(b,rewardShowLength+rewardMaxTransitionLength)}};e.resize=function(){this.calcScale(0);
var a=Math.round(this.scaleX*this.width),b=Math.round(this.scaleY*this.height);q.style.width=a+"px";q.style.height=b+"px";for(var c=0;c<backupStates.length;c++)canvases[c].width=a,canvases[c].height=b,this.canvasManager.initContext(this.contexts[c],this.scaleX,this.scaleY);this.canvasManager.drawMapSegments(this.contexts[0]);for(c in k)this.canvasManager.drawPencilSegments(this.contexts[0],k[c]);this.correctionTick=-backupStates[1]-1;this.revertBackup()};e.displayDebugStatus=function(){displayDebugStatus&&
this.domManager.setDebugMessage("FPS: + "+fps+"<br/>Reverts: "+A+"<br/>Modified inputs: "+F+"<br/>Time adjustments: "+z)};e.backToGameLobby=function(){for(var a in k){var b=k[a];"left"==b.status?this.removePlayer(b):(b.status=b.isHost?"host":"ready",b.points=0,b.updateRow())}};e.copyGamePos=function(a,b){b.x=a.pageX;b.y=a.pageY;b.subtract(this.domManager.findPos(a.target));b.x=Math.round(Math.max(Math.min(this.width,b.x/this.scaleX),0));b.y=Math.round(Math.max(Math.min(this.height,b.y/this.scaleY),
0));return b};e.getGamePos=function(a){var b=new Vector(0,0);this.copyGamePos(a,b);return b};return e}();function touchEvent(a,b,c){this.startX=a;this.startY=b;this.identifier=c}
function InputController(a,b,c){function f(a){a.identifier=1;return{changedTouches:[a]}}function d(a){k.copyGamePos(a,j);emulateTouch?m(f(a)):o.raise()}function g(a){if("playing"!=k.state)"countdown"==k.state&&a.cancelable&&a.preventDefault();else{for(var b=0;b<a.changedTouches.length;b++){var c=a.changedTouches[b],d=k.getGamePos(c),f=k.width,g=d.x<=f*steerBoxSize,f=d.x>=(1-steerBoxSize)*f;"alive"==h.player.status&&f&&null===h.leftTouch?(h.leftTouch=new touchEvent(d.x,d.y,c.identifier),h.pressLeft()):
"alive"==h.player.status&&g&&null===h.rightTouch?(h.rightTouch=new touchEvent(d.x,d.y,c.identifier),h.pressRight()):null==h.pencilTouch&&o.isLowerable()&&(h.pencilTouch=new touchEvent(d.x,d.y,c.identifier),d.copyTo(j),o.lower())}a.cancelable&&a.preventDefault()}}function m(a){if("playing"!=k.state)"countdown"==k.state&&a.cancelable&&a.preventDefault();else{for(var b=0;b<a.changedTouches.length;b++){var c=a.changedTouches[b];"alive"==h.player.status&&null!=h.leftTouch&&c.identifier==h.leftTouch.identifier?
(h.releaseLeft(),h.leftTouch=null):"alive"==h.player.status&&null!=h.rightTouch&&c.identifier==h.rightTouch.identifier?(h.releaseRight(),h.rightTouch=null):null!=h.pencilTouch&&c.identifier==h.pencilTouch.identifier&&(o.raise(),h.pencilTouch=null)}a.cancelable&&a.preventDefault()}}function i(a){if("playing"!=k.state)"countdown"==k.state&&a.cancelable&&a.preventDefault();else{for(var b=0;b<a.changedTouches.length;b++){var c=a.changedTouches[b],d=k.getGamePos(c),f=k.width,g=d.x<=f*steerBoxSize,f=d.x>=
(1-steerBoxSize)*f;if(null!=h.leftTouch&&c.identifier==h.leftTouch.identifier){var i=getLength(d.x-h.leftTouch.startX,d.y-h.leftTouch.startY)>=pencilTreshold&&null==h.pencilTouch&&o.isLowerable();i&&(h.pencilTouch=new touchEvent(d.x,d.y,c.identifier),d.copyTo(j),o.lower());if(i||!f)h.releaseLeft(),h.leftTouch=null}else if(null!=h.rightTouch&&c.identifier==h.rightTouch.identifier){if(i=getLength(d.x-h.rightTouch.startX,d.y-h.rightTouch.startY)>=pencilTreshold&&null==h.pencilTouch&&o.isLowerable())h.pencilTouch=
new touchEvent(d.x,d.y,c.identifier),d.copyTo(j),o.lower();if(i||!g)h.releaseRight(),h.rightTouch=null}else null!=h.pencilTouch&&c.identifier==h.pencilTouch.identifier&&d.copyTo(j)}a.cancelable&&a.preventDefault()}}this.rightKeyCode=b;this.leftKeyCode=c;this.player=a;this.rightDown=this.leftDown=!1;this.pencilTouch=this.rightTouch=this.leftTouch=null;this.lastSteerTick=-1;this.lastSteerTurn=0;var h=this,k=a.game,j=k.mouse,l=k.editor,o=k.pencil,a=document.getElementById("baseCanvas");window.addEventListener("keydown",
function(a){"editing"==k.state&&document.activeElement!=k.chatBar?l.handleKeyEvent(a):"alive"!=h.player.status||"playing"!=k.state||(a.keyCode==h.leftKeyCode?(h.pressLeft(),a.preventDefault()):a.keyCode==h.rightKeyCode&&(h.pressRight(),a.preventDefault()))},!1);window.addEventListener("keyup",function(a){"alive"!=h.player.status||"playing"!=k.state||(a.keyCode==h.leftKeyCode?(h.releaseLeft(),a.preventDefault()):a.keyCode==h.rightKeyCode&&(h.releaseRight(),a.preventDefault()))},!1);touchDevice&&(a.addEventListener("touchstart",
g,!1),a.addEventListener("touchend",m,!1),a.addEventListener("touchcancel",m,!1),a.addEventListener("touchmove",i,!1));a.addEventListener("mousedown",function(a){if(emulateTouch)g(f(a));else{k.copyGamePos(a,j);o.lower();a.cancelable&&a.preventDefault()}},!1);a.addEventListener("mousemove",function(a){emulateTouch?i(f(a)):k.copyGamePos(a,j)},!1);a.addEventListener("mouseup",d,!1);a.addEventListener("mouseout",d,!1)}
InputController.prototype.reset=function(){this.rightDown=this.leftDown=!1;this.pencilTouch=this.rightTouch=this.leftTouch=null;this.lastSteerTick=-1;this.lastSteerTurn=0};InputController.prototype.pressLeft=function(){this.leftDown||this.steerLocal(1);this.leftDown=!0};InputController.prototype.releaseLeft=function(){this.steerLocal(this.rightDown?-1:0);this.leftDown=!1};InputController.prototype.pressRight=function(){this.rightDown||this.steerLocal(-1);this.rightDown=!0};
InputController.prototype.releaseRight=function(){this.steerLocal(this.leftDown?1:0);this.rightDown=!1};InputController.prototype.steerLocal=function(a){if(a!=this.lastSteerTurn){var b=this.player.game,c=new Turn(a,Math.ceil(b.tick),0,0,!1);this.lastSteerTick==c.tick?c.tick=++this.lastSteerTick:this.lastSteerTick=c.tick;this.lastSteerTurn=a;this.player.inputs.push(c);b.sendMsg("input",c)}};AudioController=function(){this.sounds=[];this.enableSound=!0};
AudioController.prototype.onload=function(){var a=document.getElementById("sound"),b=this,c=getCookie("sound");null!=c&"false"==c&&(a.checked=this.enableSound=!1);a.addEventListener("change",function(){b.enableSound=a.checked;setCookie("sound",a.checked?"true":"false",30)});this.addSound("countdown","sounds/countdown",["ogg","mp3"]);this.addSound("playerLeft","sounds/doorclose",["ogg","mp3"]);this.addSound("newPlayer","sounds/playerjoint",["ogg","wav"]);this.addSound("gameStart","sounds/whip",["ogg",
"mp3"]);this.addSound("localWin","sounds/winner",["ogg","mp3"]);this.addSound("chat","sounds/beep",["ogg","mp3"])};AudioController.prototype.addSound=function(a,b,c){void 0==this.sounds[a]&&(this.sounds[a]=[]);this.sounds[a].push(new buzz.sound(b,{formats:c}))};AudioController.prototype.playSound=function(a){this.enableSound&&"object"==typeof this.sounds[a]&&this.sounds[a][Math.floor(Math.random()*this.sounds[a].length)].play()};function Segment(a,b,c,f){this.x1=a;this.y1=b;this.x2=c;this.y2=f}
Segment.prototype.getLength=function(){return Math.sqrt(Math.pow(this.x2-this.x1,2)+Math.pow(this.y2-this.y1,2))};Segment.prototype.setEnd=function(a){this.x2=a.x;this.y2=a.y;return this};Segment.prototype.draw=function(a){a.moveTo(this.x1,this.y1);a.lineTo(this.x2,this.y2)};function TimedSegment(a,b,c,f,d){Segment.call(this,a,b,c,f);this.tick=d}TimedSegment.prototype=new Segment;TimedSegment.prototype.constructor=TimedSegment;
TimedSegment.prototype.print=function(){game.gameMessage("seg: "+[this.x1,this.y1,this.x2,this.y2,this.tick].join(", "))};function EditorSegment(a,b,c,f,d){Segment.call(this,a,b,c,f);this.mode=d;this.angle=0;this.teleportId=-5E3}EditorSegment.prototype=new Segment;EditorSegment.constructor=EditorSegment;Vector=function(a,b){this.x=a;this.y=b};Vector.prototype.add=function(a){this.x+=a.x;this.y+=a.y;return this};Vector.prototype.subtract=function(a){this.x-=a.x;this.y-=a.y;return this};
Vector.prototype.scale=function(a){this.x*=a;this.y*=a;return this};Vector.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};Vector.prototype.getLength=function(){return Math.sqrt(this.x*this.x+this.y*this.y)};Vector.prototype.getDistanceTo=function(a){return Math.sqrt(Math.pow(a.x-this.x,2)+Math.pow(a.y-this.y,2))};Vector.prototype.clone=function(){return new Vector(this.x,this.y)};Vector.prototype.copyTo=function(a){a.x=this.x;a.y=this.y};
Vector.prototype.link=function(a){return new Segment(this.x,this.y,a.x,a.y)};Teleporter=function(a,b,c,f,d){this.x1=a;this.y1=b;this.x2=c;this.y2=f;this.teleportId=d;this.left=Math.min(a,c);this.right=Math.max(a,c);this.top=Math.min(b,f);this.bottom=Math.max(b,f);this.tall=!1;this.dx=this.extraAngle=this.destX=this.destY=0;this.dy=1};Collision=function(a,b,c,f,d,g){this.isTeleport=a;this.collisionX=b;this.collisionY=c;this.destX=f;this.destY=d;this.extraAngle=g};
Turn=function(a,b,c,f,d){this.turn=a;this.tick=b;this.x=c;this.y=f;this.finalTurn=d};function getLength(a,b){return Math.sqrt(a*a+b*b)}function getAngle(a,b){return 0==a?0>b?3*Math.PI/2:Math.PI/2:Math.atan(b/a)+(0<a?0:Math.PI)}function rotateVector(a,b,c){return new Vector(Math.cos(c)*a-Math.sin(c)*b,Math.sin(c)*a+Math.cos(c)*b)}
function segmentCollision(a,b){if(a.x2==b.x1&&a.y2==b.y1)return-1;var c=(a.x1-a.x2)*(b.y1-b.y2)-(a.y1-a.y2)*(b.x1-b.x2);if(Math.abs(c)<epsilon)return-1;var f=((b.x2-b.x1)*(a.y1-b.y1)-(b.y2-b.y1)*(a.x1-b.x1))/c;if(0>f||1<f)return-1;c=((a.x2-a.x1)*(a.y1-b.y1)-(a.y2-a.y1)*(a.x1-b.x1))/c;return 0<=c&&1>=c?c:-1}
function createCanvasManager(a){return{drawCross:function(a,c,f){this.setLineColor(a,crossColor,1);a.lineWidth=crossLineWidth;a.beginPath();a.moveTo(c-crossSize/2,f-crossSize/2);a.lineTo(c+crossSize/2,f+crossSize/2);a.moveTo(c+crossSize/2,f-crossSize/2);a.lineTo(c-crossSize/2,f+crossSize/2);a.stroke();a.lineWidth=lineWidth},drawSegment:function(b,c,f){for(var d=0;d<backupStates.length;d++)this.strokeSegment(b,a.contexts[d],c,f)},strokeSegment:function(a,c,f,d){c.beginPath();this.setLineColor(c,f,
d);c.lineCap=1==d?lineCapStyle:"butt";a.draw(c);c.stroke();c.lineCap=lineCapStyle},drawMapSegments:function(b){b.fillStyle=canvasColor;b.fillRect(0,0,a.width,a.height);if(0<a.mapSegments.length){b.beginPath();this.setLineColor(b,mapSegmentColor,1);for(var c=0;c<a.mapSegments.length;c++){var f=a.mapSegments[c];b.moveTo(f.x1,f.y1);b.lineTo(f.x2,f.y2)}b.stroke()}for(c in a.mapTeleports)this.drawTeleport(b,a.mapTeleports[c])},drawPencilSegments:function(b,c){var f=c.pen,d=!1;this.setLineColor(b,c.color,
1);b.beginPath();for(var g=0;g<f.seg.length;g++){var m=f.seg[g];!d&&m.tick>a.tick&&(b.stroke(),this.setLineColor(b,c.color,pencilAlpha),b.beginPath(),d=!0);m.draw(b)}b.stroke()},drawTeleport:function(a,c){this.setLineColor(a,playerColors[c.teleportId],1);a.lineWidth=teleportLineWidth;var f=c.x2-c.x1,d=c.y2-c.y1,g=getLength(f,d),f=f/g,d=d/g,m=Math.max(2,Math.round((g+dashSpacing)/(dashLength+dashSpacing)));dashSpacing=(g+dashSpacing)/m-dashLength;a.beginPath();for(var g=c.x1,i=c.y1,h=0;h<m;h++)a.moveTo(g,
i),a.lineTo(g+=f*dashLength,i+=d*dashLength),g+=f*dashSpacing,i+=d*dashSpacing;a.stroke();a.lineWidth=lineWidth},drawIndicatorArrow:function(a,c,f,d,g){this.setLineColor(a,g,1);a.beginPath();a.moveTo(c,f);a.lineTo(c+=Math.cos(d)*indicatorLength,f+=Math.sin(d)*indicatorLength);a.stroke();a.fillStyle=getRGBstring(g);a.beginPath();for(var m=indicatorArrowOffset,g=indicatorArrowLength,i=a.lineWidth,h=Math.PI/4,c=c+Math.cos(d)*m,f=f+Math.sin(d)*m,m=0;2>m;m++)a.moveTo(c+Math.cos(d-h)*i,f+Math.sin(d-h)*
i),a.arc(c,f,i,d-h,d+h,!1),c+=Math.cos(d)*g,f+=Math.sin(d)*g,a.lineTo(c,f),a.closePath();a.fill()},drawDebugSegments:function(a,c){this.setLineColor(a,[0,0,0],1);a.lineWidth=1;a.beginPath();for(var f=0;f<c.length;f++){var d=c[f];d.x1!=d.x2||d.y1!=d.y2?(a.moveTo(d.x1,d.y1),a.lineTo(d.x2,d.y2)):debugZeroLengthSegs&&(a.moveTo(d.x1,d.y1),a.arc(d.x1,d.y1,5,0,2*Math.PI,!1))}a.stroke();a.lineWidth=lineWidth},initContext:function(a,c,f){a.scale(c,f);a.lineWidth=lineWidth;a.lineCap=lineCapStyle;a.drawLine=
function(c,f,m,i){a.beginPath();a.moveTo(c,f);a.lineTo(m,i);a.stroke()}},setLineColor:function(a,c,f){a.strokeStyle="rgba("+c[0]+", "+c[1]+", "+c[2]+", "+f+")"}}}window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();
function getPencilMode(){return document.getElementById("pencilOn").lastChild.checked?"on":document.getElementById("pencilOff").lastChild.checked?"off":document.getElementById("pencilOnDeath").lastChild.checked?"ondeath":null}function setPencilMode(a){var b=["pencilOn","pencilOff","pencilOnDeath"],c=0;"off"==a?c=1:"ondeath"==a&&(c=2);for(a=0;a<b.length;a++)document.getElementById(b[a]).lastChild.checked=a==c}
function setCookie(a,b,c){var f=new Date;f.setDate(f.getDate()+c);b=escape(b)+(null==c?"":"; expires="+f.toUTCString());document.cookie=a+"="+b}function getCookie(a){var b,c,f,d=document.cookie.split(";");for(b=0;b<d.length;b++)if(c=d[b].substr(0,d[b].indexOf("=")),f=d[b].substr(d[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c==a)return unescape(f)}function escapeString(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function getRGBstring(a){return"rgb("+a[0]+", "+a[1]+", "+a[2]+")"}function getRGBAstring(a,b){return"rgba("+a[0]+", "+a[1]+", "+a[2]+", "+b+")"}function printDebugPos(){for(var a="",b=0;b<debugPosA.length;b++)a+=debugPosA[b]+"<br />"+debugPosB[b]+"<br /><br />";echo(a)}function format(a,b){return(a+"0000000000000000000000000000").substr(0,b)}function simulateClick(a){var b=document.createEvent("MouseEvents");b.initMouseEvent("click",!0,!0,window,0,0,0,0,0,!1,!1,!1,!1,0,null);a.dispatchEvent(b)}
function createPencil(a,b){function c(){a.sendMsg("pencil",{data:j});j.length=0}function f(){var c=b.clone(),f=k.link(c),g=f.getLength();if(l<g+epsilon){o=!1;if(l<epsilon)return;c.subtract(k);c.scale((l-epsilon)/g);c.x=0>c.x?Math.ceil(c.x):Math.floor(c.x);c.y=0>c.y?Math.ceil(c.y):Math.floor(c.y);c.add(k);f.setEnd(c);g=f.getLength()}0!=g&&(l-=g,c.copyTo(k),d(),m.drawSegment(f,a.localPlayer.color,pencilAlpha))}function d(){j.push(k.x);j.push(k.y);j.push(Math.floor(a.tick))}function g(){i.style.height=
100*Math.max(0,l)/u+"%"}var m=a.canvasManager,b=a.mouse,i,h,k=new Vector(0,0),j=[],l,o,q,s,t,r,p,u;return{isLowerable:function(){return q&&!o&&l>s+epsilon+p},lower:function(){this.isLowerable()&&(b.copyTo(k),0<j.length&&c(),j.push(-1),d(),o=!0,l-=s)},raise:function(){o&&(f(),o=!1)},enable:function(b){h.style.display="block";q=!0;l=r+t*(Math.floor(a.tick)-b);g()},reset:function(){j.length=0;q=o=!1;h.style.display="none"},doTick:function(){q&&(o&&k.getDistanceTo(b)>p+epsilon&&f(),l=Math.min(u,l+t),
g(),0<j.length&&0==Math.floor(a.tick)%inkBufferTicks&&c())},setParameters:function(b){b.inkMinimumDistance?p=b.inkMinimumDistance:(s=b.inkmousedown,t=b.inkregen/1E3*a.tickLength,r=b.inkstart,u=b.inkcap)},updateColor:function(){i.style.backgroundColor=getRGBAstring(a.localPlayer.color,0.5)},onload:function(){i=document.getElementById("ink");h=document.getElementById("inkIndicator")}}}var Pen=function(a){this.seg;this.pos;this.visibleIndex=this.solidIndex=0;this.player=a};
Pen.prototype.reset=function(){this.seg=[];this.pos=new Vector(0,0);this.visibleIndex=this.solidIndex=0};Pen.prototype.doTick=function(){var a=this.player.game.canvasManager,b=this.player.game.tick;if(!this.player.isLocal)for(;this.visibleIndex<this.seg.length;)a.drawSegment(this.seg[this.visibleIndex++],this.player.color,pencilAlpha);for(;this.solidIndex<this.seg.length&&this.seg[this.solidIndex].tick<=b;)a.drawSegment(this.seg[this.solidIndex++],this.player.color,1)};
PlayerState=function(a){this.player=a;this.dy=this.dx=this.inHole=this.nextInputIndex=this.tick=this.velocity=this.turn=this.angle=this.y=this.x=0};PlayerState.prototype.copyState=function(a){this.x=a.x;this.y=a.y;this.angle=a.angle;this.turn=a.turn;this.velocity=a.velocity;this.tick=a.tick;this.nextInputIndex=a.nextInputIndex;this.inHole=a.inHole;this.dx=a.dx;this.dy=a.dy;this.tped=a.tped};
PlayerState.prototype.changeCourse=function(a){var b=this.player.game.tickLength;this.angle+=a;this.dx=Math.cos(this.angle)*this.velocity*b/1E3;this.dy=Math.sin(this.angle)*this.velocity*b/1E3};
Player=function(a,b){this.game=a;this.inputController=(this.isLocal=b)?new InputController(this,keyCodeLeft,keyCodeRight):null;this.states=Array(backupStates.length);this.pen=new Pen(this);this.status=this.holeColor=this.segColor="#FFF";this.status="ready";this.inputs=[];this.color=[];this.points=this.holeStart=this.holeSize=this.holeFreq=this.lastInputTick=this.lastInputTurn=this.finalTick=this.turnSpeed=0;this.isHost=!1;for(var c=0;c<backupStates.length;c++)this.states[c]=new PlayerState(this)};
Player.prototype.finalSteer=function(a){for(var b=a.tick,c=this.inputs.length-1;0<=c&&this.inputs[c].tick>=b;c--);this.inputs.length=c+2;this.inputs[c+1]=new Turn(0,b,a.x,a.y,!0);this.finalTick=b;b<=Math.ceil(this.states[backupStates.length-1].tick)&&(this.game.correctionTick=Math.min(this.game.correctionTick,b))};Player.prototype.setSegmentStyle=function(a,b){a.strokeStyle=b?this.holeColor:this.segColor;a.lineCap=b?"butt":"round"};
Player.prototype.simulate=function(a,b,c){if(!(c.tick>a||c.tick>this.finalTick)){var f=this.inputs[c.nextInputIndex];for(this.setSegmentStyle(b,c.inHole);c.tick<a;){var d=c.tick==Math.floor(c.tick);if(d){var g=c.tick>this.holeStart&&(c.tick+this.holeStart)%(this.holeSize+this.holeFreq)<this.holeSize;g!=c.inHole&&(c.inHole=g,this.setSegmentStyle(b,g));c.tped=!1}if(!c.tped){this.game.torus&&d&&((c.x>this.game.width?c.x=0:0>c.x&&(c.x=this.game.width),c.y>this.game.height)?c.y=0:0>c.y&&(c.y=this.game.height));
if(d&&null!=f&&f.tick==c.tick)if(f.finalTurn){b.drawLine(c.x,c.y,f.x,f.y);this.game.crossQueue.push(c.x=f.x);this.game.crossQueue.push(c.y=f.y);c.tick++;break}else c.turn=f.turn,f=this.inputs[++c.nextInputIndex];d&&0!=c.turn&&c.changeCourse(c.turn*this.turnSpeed*this.game.tickLength/1E3);var g=Math.min(1,a-c.tick),d=c.x+c.dx*g,g=c.y+c.dy*g,m=this.game.getCollision(c.x,c.y,d,g),i=!1;null!=m&&m.isTeleport&&(b.drawLine(c.x,c.y,m.collisionX,m.collisionY),c.changeCourse(m.extraAngle),c.x=m.destX+Math.cos(c.angle)/
10,c.y=m.destY+Math.sin(c.angle)/10,i=c.tped=!0);i||b.drawLine(c.x,c.y,c.x=d,c.y=g)}c.tick=Math.min(Math.floor(c.tick+1),a)}}};Player.prototype.updateRow=function(){"left"==this.status&&(this.row.className="left");"lobby"!=this.game.type&&(this.row.childNodes[0].style.color=getRGBstring(this.color));this.row.childNodes[1].innerHTML=this.status;this.row.childNodes[2].innerHTML=this.points};
Player.prototype.initialise=function(a,b,c,f){var d=this.states[0];d.velocity=this.game.velocity;d.inHole=!1;d.x=a;d.y=b;d.nextInputIndex=0;d.angle=c;d.changeCourse(0);d.turn=0;d.tick=0;d.tped=!1;for(a=1;a<backupStates.length;a++)this.states[a].copyState(d);this.status="alive";this.inputs.length=0;this.lastInputTick=-1;this.lastInputTurn=0;this.finalTick=Infinity;this.turnSpeed=this.game.turnSpeed;this.holeStart=f;this.holeSize=this.game.holeSize;this.holeFreq=this.game.holeFreq;this.pen.reset();
this.updateRow();null!=this.inputController&&this.inputController.reset()};
Player.prototype.drawIndicator=function(){var a=this.game.baseContext,b=this.states[0].x,c=this.states[0].y,f=this.states[0].angle;this.game.canvasManager.drawIndicatorArrow(a,b,c,f,this.color);var d=this.isLocal?"YOU":this.playerName;a.fillStyle=getRGBstring(this.color);a.font="bold "+indicatorFont+"px Helvetica, sans-serif";a.textBaseline="bottom";var g=a.measureText(d).width,b=b-(0<Math.cos(f)&&0>Math.sin(f)?g+2:0);a.fillText(d,Math.min(this.game.width-g,Math.max(0,b)),c-3)};
